### ISSUE TITLE
Is there a way to map an object using a keypath with RxSwift?

### ISSUE THREAD

**Issue by mcontin** [bmoliveira/Moya-ObjectMapper#78]
I'm trying to map an object using RxSwift with a keypath like you would do with ObjectMapper.
I tried with .mapString first but since it returns a Single\<String\> I can't chain .mapObject which expects a Single\<Response\>.
Should I implement an extension by myself or am I missing something?

**Comment by chengxianghe** [comment]
use JSONDecoder and map<D: Decodable> 
https://github.com/Moya/Moya/blob/master/Sources/RxMoya/Single%2BResponse.swift
last func.
